number1 = input('Введите первое число:')
number2 = input('Введите второе число:')
number3 = input('Введите 3 число:')
print('Количество отрицательных знаков', (number1+number2+number3).count('-'))
#total = ((number1+number2+number3).count('-'))
#print('Количество отрицательных знаков', total)
